export const optionsCategoria=[
    { value: "0", label: "" },
    { value: "1", label: "Administración de empresas" },
    { value: "2", label: "Atención a clientes " },
    { value: "3", label: "Calidad, producción e I+D " },
    { value: "4", label: "Comercial y ventas " },
    { value: "5", label: "Compras, logística y almacén" },
    { value: "6", label: "Diseño y artes gráficas " },
    { value: "7", label: "Educación y formación " },
    { value: "8", label: "Finanzas y banca " },
    { value: "9", label: "Informática y telecomunicaciones" },
    { value: "10", label: "Ingenieros y técnicos " },
    { value: "11", label: "Inmobiliario y construcción" }, 
    { value: "12", label: "Legal " },
    { value: "13", label: "Marketing y comunicación " },
    { value: "14", label: "Profesiones, artes y oficios " },
    { value: "15", label: "Recursos humanos " },
    { value: "16", label: "Sanidad y salud " },
    { value: "17", label: "Sector Farmacéutico " },
    { value: "18", label: "Turismo y restauración " },
    { value: "19", label: "Ventas al detalle " },
    { value: "20", label: "Otros " }
]

export const optionsProvincia=[
    { value:"0",label: ""},
    { value:"1",label: "Toda España" },
    { value:"2",label: "En el extranjero" },
    { value:"3",label: "Madrid" },
    { value:"4",label: "Barcelona "},
    { value:"5",label: "Valencia/València" },
    { value:"6",label: "Sevilla" },
    { value:"7",label: "A Coruña" },
    { value:"8",label: "Álava/Araba" },
    { value:"9",label: "Albacete"},
    { value:"10", label: "Alicante/Alacant "},
    { value:"11", label: "Almería "},
    { value:"12", label: "Asturias "},
    { value:"13", label: "Ávila "},
    { value:"14", label: "Badajoz"},
    { value:"15", label: "Barcelona "},
    { value:"16", label: "Burgos"},
    { value:"17", label: "Cáceres "},
    { value:"18", label: "Cádiz"},
    { value:"19", label: "Cantabria "},
    { value:"20", label: "Castellón/Castelló"},
    { value:"21", label: "Ceuta "},
    { value:"22", label: "Ciudad Real"},
    { value:"23", label: "Córdoba"},
    { value:"24", label: "Cuenca"},
    { value:"25", label: "Girona"},
    { value:"26", label: "Granada "},
    { value:"27", label: "Guadalajara "},
    { value:"29", label: "Guipúzcoa/Gipuzkoa"},
    { value:"30", label: "Huelva "},
    { value:"31", label: "Huesca "},
    { value:"32", label: "Islas Baleares/Illes Balears"},
    { value:"33", label: "Jaén"},
    { value:"34", label: "La Rioja"},
    { value:"35", label: "Las Palmas"},
    { value:"36", label: "León "},
    { value:"37", label: "Lleida "},
    { value:"38", label: "Lugo "},
    { value:"39", label: "Madrid"},
    { value:"40", label: "Málaga "},
    { value:"41", label: "Melilla "},
    { value:"42", label: "Murcia"},
    { value:"43", label: "Navarra"},
    { value:"44", label: "Ourense"},
    { value:"45", label: "Palencia "},
    { value:"46", label: "Pontevedra "},
    { value:"47", label: "Salamanca "},
    { value:"48", label: "Santa Cruz de Tenerife"},
    { value:"49", label: "Segovia"},
    { value:"50", label: "Sevilla "},
    { value:"51", label: "Soria "},
    { value:"52", label: "Tarragona "},
    { value:"53", label: "Teruel "},
    { value:"54", label: "Toledo "},
    { value:"55", label: "Valencia/València"},
    { value:"56", label: "Valladolid "},
    { value:"57", label: "Vizcaya/Bizkaia "},
    { value:"58", label: "Zamora "},
    { value:"59", label: "Zaragoza "}
]


